services:

  backend:
    container_name: backend
    networks:
      - transcendence
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - transcendence
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    networks:
      - transcendence
    build:
      context: .          # Contexte racine du projet pour englober aussi le dossier frontend 
      dockerfile: nginx/Dockerfile  # Spécifie le Dockerfile dans le dossier nginx
    ports:
      - "8080:80"    # HTTP redirigé vers HTTPS
      - "8443:443"   # HTTPS sur 8443 pour éviter le besoin de sudo
    depends_on:
      - backend
    volumes:
      - ./nginx/certs/selfsigned.crt:/etc/nginx/selfsigned.crt
      - ./nginx/certs/selfsigned.key:/etc/nginx/selfsigned.key

networks:
  transcendence:
    driver: bridge

volumes:
  postgres_data:
    driver: local
