services:
  frontend:
    container_name: frontend
    networks:
      - transcendence
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    container_name: backend
    networks:
      - transcendence
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - transcendence
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate"


networks:
  transcendence:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${GOINFRE_PATH}/"
