services:
  frontend:
    container_name: frontend
    networks:
      - transcendence
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    container_name: backend
    networks:
      - transcendence
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - transcendence
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


networks:
  transcendence:
    driver: bridge

# volumes:
#   postgres_data:
#     driver: local