# Generated by Django 5.1.3 on 2025-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, help_text='Required for Email 2FA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Time when OTP was generated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Required for SMS 2FA', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('TOTP', 'Google Authenticator')], help_text='2FA method choosed by user', max_length=10, null=True),
        ),
    ]
