# Generated by Django 5.1.3 on 2025-01-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='unnamed', max_length=100, unique=True),
        ),
    ]
