# Generated by Django 5.1.3 on 2025-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_is_active_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default='EN', max_length=3),
        ),
    ]
