# Generated by Django 5.1.3 on 2025-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_user_email_otp_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, help_text='Required for Email 2FA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('TOTP', 'Google Authenticator'), ('none', 'None')], help_text='2FA method choosed by user', max_length=10, null=True),
        ),
    ]
