# Generated by Django 5.1.3 on 2025-01-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_match_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='match_history',
            field=models.ManyToManyField(blank=True, related_name='match_history', to='api.game'),
        ),
    ]
