# Generated by Django 5.1.3 on 2025-01-14 10:32

import api.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_model.file_location),
        ),
    ]
