export const trad = {
  EN: {
    account: {
      pageTitle: "Account",
      fileLabel: "Upload image",
      username: "Username",
      alias: "Alias",
      totp2faLabel: "2FA with Google Authenticator",
      email2faLabel: "2FA with e-mail",
      sms2faLabel: "2FA with SMS",
      change: "Change my information",
      cancel: "Cancel",
      update: "Update my information",
      delete: "Delete my account",
      sure: "Are you sure ?",
      yes: "Yes",
      no: "No",
    },
    game: {
      pvp: "Player vs Player",
      pvr: "Player vs Robot",
      local: "Local tournament",
      paused: "Game paused",
      resume: "Resume game",
      quit: "Quit game",
      leftWins: "Left player wins !",
      rightWins: "Right player wins !",
      playAgain: "Play again",
      back: "Back to menu",
    },
    home: {
      play: "Play",
      login: "Login",
      guestMode: "Guest Mode",
    },
  },
  FR: {
    account: {
      pageTitle: "Compte",
      fileLabel: "Modifier l'image",
      username: "Nom",
      alias: "Alias",
      totp2faLabel: "2FA avec Google Authenticator",
      email2faLabel: "2FA avec e-mail",
      sms2faLabel: "2FA avec SMS",
      change: "Changer mes informations",
      cancel: "Annuler",
      update: "Mettre à jour mes informations",
      delete: "Supprimer mon compte",
      sure: "Confirmer ?",
      yes: "Oui",
      no: "Non",
    },
    game: {
      pvp: "Joueur vs Joueur",
      pvr: "Joueur vs Robot",
      local: "Tournoi local",
      paused: "Jeu en pause",
      resume: "Reprendre",
      quit: "Quitter le jeu",
      leftWins: "Le joueur de gauche gagne !",
      rightWins: "Le joueur de droite gagne !",
      playAgain: "Recommencer",
      back: "Retour au menu",
    },
    home: {
      play: "Jouer",
      login: "Se connecter",
      guestMode: "Mode invité",
    },
  },
};
