export const trad = {
  EN: {
    account: {
      pageTitle: "Account",
      fileLabel: "Upload image",
      username: "Username",
      alias: "Alias",
      totp2faLabel: "2FA with Google Authenticator",
      email2faLabel: "2FA with e-mail",
      sms2faLabel: "2FA with SMS",
      change: "Change my information",
      cancel: "Cancel",
      update: "Update my information",
      delete: "Delete my account",
      sure: "Are you sure ?",
      yes: "Yes",
      no: "No",
    },
    home: {
      play: "Play",
      login: "Login",
      guestMode: "Guest Mode",
    },
  },
  FR: {
    account: {
      pageTitle: "Compte",
      fileLabel: "Modifier l'image",
      username: "Nom",
      alias: "Alias",
      totp2faLabel: "2FA avec Google Authenticator",
      email2faLabel: "2FA avec e-mail",
      sms2faLabel: "2FA avec SMS",
      change: "Changer mes informations",
      cancel: "Annuler",
      update: "Mettre à jour mes informations",
      delete: "Supprimer mon compte",
      sure: "Confirmer ?",
      yes: "Oui",
      no: "Non",
    },
    home: {
      play: "Jouer",
      login: "Se connecter",
      guestMode: "Mode invité",
    },
  },
};
