export const trad = {
  EN: {
    header: {
      home: "Home",
      play: "Play",
      account: "Account",
      stats: "Stats",
      matchHistory: "Match History",
      social: "Social",
      register: "Register",
      login: "Login",
      logout: "Logout",
    },
    account: {
      pageTitle: "Account",
      fileLabel: "Upload image",
      username: "Username",
      alias: "Alias",
      totp2faLabel: "2FA with Google Authenticator",
      email2faLabel: "2FA with e-mail",
      sms2faLabel: "2FA with SMS",
      change: "Change my information",
      cancel: "Cancel",
      update: "Update my information",
      delete: "Delete my account",
      sure: "Are you sure ?",
      yes: "Yes",
      no: "No",
    },
    game: {
      pvp: "Player vs Player",
      pvr: "Player vs Robot",
      local: "Local tournament",
      paused: "Game paused",
      resume: "Resume game",
      quit: "Quit game",
      leftWins: "Left player wins !",
      rightWins: "Right player wins !",
      playAgain: "Play again",
      back: "Back to menu",
    },
    home: {
      play: "Play",
      login: "Login",
      guestMode: "Guest Mode",
    },
    localTournament: {
      playersNum: "Number of Players",
      select: "Select...",
      player: "Player n°",
      namePlayer: "Name for player n°",
      winner: "Winner :",
      final: "FINAL",
      round: "Round n°",
      play: "PLAY",
      gameMenu: "Game menu",
      stop: "Stop Tournament",
    },
    login: {
      pageTitle: "Login",
      label2fa: "We've sent a verification code to your ",
      oneTimeCode: "Enter verification code",
      login: "Login",
      retry: "Retry",
      enterUsername: "Enter username",
      enterPassword: "Enter password",
      register: "No account ? Create one here",
    },
    matchHistory: {
      pageTitle: "Match History",
      won: "won",
      lost: "lost",
      noContent: "No match history",
    },
    register: {
      pageTitle: "Register",
      enterUsername: "Enter username",
      enterPassword: "Enter password",
      confirmPassword: "Confirm Password",
      signUp: "Sign up",
      restrictions:
        "Password must have at least 8 characters, one uppercase letter, one number, and one special character",
    },
    social: {
      pageTitle: "Social",
      search: "Search...",
      friends: "FRIENDS",
      online: "Online",
      offline: "Offline",
      noFriends: "Zero friend, sniff sniff",
      requests: "REQUESTS",
      waitingAcceptation: ", waiting for acceptation...",
      noInvitation: "No pending invitations",
    },
    stats: {
      pageTitle: "Stats",
      wins: "Wins",
      losses: "Losses",
      winRatio: "Win ratio",
      gameNum: "Number of games",
      averageScore: "Average score",
      lastGame: "Last game",
    },
    user: {
      pageTitle: "User",
      username: "Username :",
      alias: "Alias :",
      addFriend: "Add friend",
      unfriend: "Unfriend",
      cancel: "Cancel friend request",
      accept: "Accept friend request",
      delete: "Delete friend request",
    },
  },
  FR: {
    header: {
      home: "Accueil",
      play: "Jouer",
      account: "Compte",
      stats: "Stats",
      matchHistory: "Historique de jeu",
      social: "Amis",
      register: "S'inscrire",
      login: "Connexion",
      logout: "Déconnexion",
    },
    account: {
      pageTitle: "Compte",
      fileLabel: "Modifier l'image",
      username: "Nom",
      alias: "Alias",
      totp2faLabel: "2FA avec Google Authenticator",
      email2faLabel: "2FA avec e-mail",
      sms2faLabel: "2FA avec SMS",
      change: "Changer mes informations",
      cancel: "Annuler",
      update: "Mettre à jour mes informations",
      delete: "Supprimer mon compte",
      sure: "Confirmer ?",
      yes: "Oui",
      no: "Non",
    },
    game: {
      pvp: "Joueur vs Joueur",
      pvr: "Joueur vs Robot",
      local: "Tournoi local",
      paused: "Jeu en pause",
      resume: "Reprendre",
      quit: "Quitter le jeu",
      leftWins: "Le joueur de gauche gagne !",
      rightWins: "Le joueur de droite gagne !",
      playAgain: "Recommencer",
      back: "Retour au menu",
    },
    home: {
      play: "Jouer",
      login: "Se connecter",
      guestMode: "Mode invité",
    },
    localTournament: {
      playersNum: "Nombre de joueurs",
      select: "Selection...",
      player: "Joueur n°",
      namePlayer: "Nom du joueur n°",
      winner: "Gagnant :",
      final: "FINALE",
      round: "Tour n°",
      play: "JOUER",
      gameMenu: "Menu du jeu",
      stop: "Arrêter le tournoi",
    },
    login: {
      pageTitle: "Connexion",
      label2fa: "Nous avons envoyé un code sur votre ",
      oneTimeCode: "Saisir le code",
      login: "Se connecter",
      retry: "Retour",
      enterUsername: "Saisir votre nom",
      enterPassword: "Saisir votre mot de passe",
      register: "Pas de compte ? En créer un ici",
    },
    matchHistory: {
      pageTitle: "Historique de jeu",
      won: "gagné",
      lost: "perdu",
      noContent: "Pas d'historique de jeu",
    },
    register: {
      pageTitle: "Créer un compte",
      enterUsername: "Saisir votre nom",
      enterPassword: "Saisir votre mot de passe",
      confirmPassword: "Confirmer votre mot de passe",
      signUp: "Créer un compte",
      restrictions:
        "Le mot de passe doit comporter au moins 8 caractères, une lettre majuscule, un chiffre et un caractère spécial",
    },
    social: {
      pageTitle: "Amis",
      search: "Recherche...",
      friends: "AMIS",
      online: "En ligne",
      offline: "Hors ligne",
      noFriends: "Pas d'amis, sniff sniff",
      requests: "DEMANDES",
      waitingAcceptation: ", en attente d'acceptation...",
      noInvitation: "Pas d'invitations en attente",
    },
    stats: {
      pageTitle: "Statistiques",
      wins: "Victoires",
      losses: "Défaites",
      winRatio: "Ratio de victoires",
      gameNum: "Nombre de parties",
      averageScore: "Score moyen",
      lastGame: "Dernière partie",
    },
    user: {
      pageTitle: "Utilisateur",
      username: "Nom :",
      alias: "Alias :",
      addFriend: "Ajouter",
      unfriend: "Retirer",
      cancel: "Annuler l'invitation'",
      accept: "Accepter l'invitation",
      delete: "Refuser l'invitation",
    },
  },
};
